name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          [
            aarch64-linux-musl-cross.tgz
            # aarch64_be-linux-musl-cross.tgz
            # arch64-linux-musl-cross.tgz
            # arm-linux-musleabi-cross.tgz
            # arm-linux-musleabihf-cross.tgz
            # armeb-linux-musleabi-cross.tgz
            # armeb-linux-musleabihf-cross.tgz
            # armel-linux-musleabi-cross.tgz
            # armel-linux-musleabihf-cross.tgz
            # armv5l-linux-musleabi-cross.tgz
            # armv5l-linux-musleabihf-cross.tgz
            # armv6-linux-musleabihf-cross.tgz
            # armv7l-linux-musleabihf-cross.tgz
            # armv7m-linux-musleabi-cross.tgz
            # armv7r-linux-musleabihf-cross.tgz
            # h2eb-linux-musl-cross.tgz
            # h2eb-linux-muslfdpic-cross.tgz
            # i486-linux-musl-cross.tgz
            # i686-linux-musl-cross.tgz
            # i686-w64-mingw32-cross.tgz
            # m68k-linux-musl-cross.tgz
            # microblaze-linux-musl-cross.tgz
            # microblazeel-linux-musl-cross.tgz
            # mips-linux-musl-cross.tgz
            # mips-linux-musln32sf-cross.tgz
            # mips-linux-muslsf-cross.tgz
            # mips64-linux-musl-cross.tgz
            # mips64-linux-musln32-cross.tgz
            # mips64-linux-musln32sf-cross.tgz
            # mips64el-linux-musl-cross.tgz
            # mips64el-linux-musln32-cross.tgz
            # mips64el-linux-musln32sf-cross.tgz
            # mipsel-linux-musl-cross.tgz
            # mipsel-linux-musln32-cross.tgz
            # mipsel-linux-musln32sf-cross.tgz
            # mipsel-linux-muslsf-cross.tgz
            # or1k-linux-musl-cross.tgz
            # powerpc-linux-musl-cross.tgz
            # powerpc-linux-muslsf-cross.tgz
            # powerpc64-linux-musl-cross.tgz
            # powerpc64le-linux-musl-cross.tgz
            # powerpcle-linux-musl-cross.tgz
            # powerpcle-linux-muslsf-cross.tgz
            # riscv32-linux-musl-cross.tgz
            # riscv64-linux-musl-cross.tgz
            # s390x-linux-musl-cross.tgz
            # sh2-linux-musl-cross.tgz
            # sh2-linux-muslfdpic-cross.tgz
            # sh4-linux-musl-cross.tgz
            # sh4eb-linux-musl-cross.tgz
            # x86_64-linux-musl-cross.tgz
            # x86_64-linux-muslx32-cross.tgz
            # x86_64-w64-mingw32-cross.tgz
          ]
    env:
      CC: ${{ matrix.target }}-gcc
      STRIP: ${{ matrix.target }}-strip
      BIN_NAME: hello
      RELEASE_BIN: ${{ env.BIN_NAME }}-${{ github.ref_name }}-${{ matrix.target }}
    steps:
    - uses: actions/checkout@v2
    - name: Download cross compiler
      run: |
        curl -O https://muslcc.netlify.app/${{ matrix.target }}-cross.tgz
        tar xzf ${{ matrix.target }}-cross.tgz -C /opt
    - name: add compiler to PATH
    - run: echo "/opt/${{ matrix.target }}-cross/bin/" >> $GITHUB_PATH
    - name: Echo gcc version
    - run: ${{ matrix.target }}-gcc --verbose
    - name: build binary
      run: |
        CFLAGS="-static -O2" ${{ env.CC }} main.c -o hello
    - name: strip binary
      run: |
        ${{ env.STRIP }} hello || true
    - name: rename binary for release
      run: |
        mv ${{ env.BIN_NAME }} ${{ env.RELEASE_BIN }}
        file ${{ env.RELEASE_BIN }}
    - name: Publish archives and packages
      uses: softprops/action-gh-release@v1
      with:
        files: "${{ env.RELEASE_BIN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
