name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [ aarch64-linux-musl ]
    env:
      CC: ${{ matrix.target }}-gcc
    steps:
    - uses: actions/checkout@v2
    - name: Download cross compiler
      run: |
        curl -O http://musl.cc/${{ matrix.target}}-cross.tgz
        tar xzf ${{ matrix.target }}-cross.tgz -C /opt
    - run: echo "/opt/${{ matrix.target }}-cross/bin/" >> $GITHUB_PATH
    - run: ${{ matrix.target }}-gcc --version
    - name: build binary
      run: |
        CFLAGS="-static" cc main.c -o hello
        ${{ matrix.target }}-strip hello || true
        mv hello ${{ matrix.target }}-hello
        file ./${{ matrix.target }}-hello
    - name: Publish archives and packages
      uses: softprops/action-gh-release@v1
      with:
        files: "${{ matrix.target }}-hello"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
