name: Release

on: [push]

jobs:
  build_cosmopolitan:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        wget https://justine.lol/cosmopolitan/cosmopolitan-amalgamation-1.0.zip
        unzip cosmopolitan-amalgamation-1.0.zip
        gcc -g -Os -static -nostdlib -nostdinc -fno-pie -no-pie -mno-red-zone \
          -fno-omit-frame-pointer -pg -mnop-mcount \
          -o hello.com.dbg hello.c -fuse-ld=bfd -Wl,-T,ape.lds \
          -include cosmopolitan.h crt.o ape.o cosmopolitan.a
        objcopy -S -O binary hello.com.dbg hello.com
        file ./hello.com
